apiVersion: v2
name: kueue-setup
description: A Helm chart for Kueue job queue management with customizable configuration
type: application
version: 1.0.0
appVersion: "0.13.0"
kubeVersion: ">=1.25.0-0"
home: https://github.com/milaboratory/platforma-helm-charts
sources:
  - https://github.com/milaboratory/platforma-helm-charts/charts/kueue-setup
keywords:
  - kueue
  - kubernetes
  - job-queue
  - batch
  - scheduling
annotations:
  artifacthub.io/links: |-
    - name: Kueue Documentation
      url: https://kueue.sigs.k8s.io/docs
    - name: Charts repository
      url: https://github.com/milaboratory/platforma-helm-charts

dependencies:
  - name: kueue
    alias: kueue-controller
    version: "0.13.0"
    repository: "oci://registry.k8s.io/kueue/charts"
    condition: controller.enabled
